config/routes.rb
Rails.application.routes.draw do

  #Authentification
  get 'signup' => 'users#new'
  resources :users
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'home#index'
  get 'home/index' => 'home#index'
  get 'home/page_actions' =>'home#page_actions'
  get 'promo' =>'home#promo'
  get 'promo2' =>'home#promo2'
  get 'projets' =>'home#projets'

  resource :sessions
  #Projet Blog
  resources :articles do
    resources :comments
  end 


  #Projet Réservation-Intervenants
  get '/intervenants' => 'calendrier#show'
  get '/intervenants/reservation/:day-:month' => 'calendrier#reservation'
  post '/intervenants/reservation' => 'calendrier#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :day, :month, :year,:content, presence: true
	validates :title, presence: true
	validates :subtitle, presence: true
end

app/models/calendrier.rb
class Calendrier < ActiveRecord::Base
	validates :nom, presence: true
 	validates :prenom, presence: true
	validates :date, presence: true, uniqueness: true
end

app/models/citation.rb
class Citation < ActiveRecord::Base
	has_one :citations
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name,  presence: true
  validates_uniqueness_of :name
	has_secure_password

  scope :simploniens, -> {
    where(:online => true)
  }

  def tags_to_array
    self.tags.split(",")
  end

  def image_path
    first_name = self.name.split.first.downcase
    "simploniens/#{first_name}.jpg"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
   	@articles = Article.all
  end
	
  def new
    @article = Article.new
	end
	
  def create
		@article = Article.new(article_params)
    if @article.save
      redirect_to articles_path, notice: "L'article a été créé"
    else
      redirect_to new_article_path
    end
	end
	
  def show
		@article = Article.find(params[:id])
	end
	
  def edit
  	@article = Article.find(params[:id])
  end
	
  def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
  		redirect_to articles_path
		else
  		render 'edit'
		end
	end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

 	private
	
  def article_params
  	params.require(:article).permit(:day, :month, :year, :title, :subtitle, :content)
	end
end

app/controllers/calendrier_controller.rb
class CalendrierController < ApplicationController

	def show
		@intervenant = Calendrier.all.order("date")
		@month = {"06"=>["Juin", "June", 30, 1], "07"=>["Juillet", "July", 31, 3], "08"=>["Août", "August", 31, 6], "09"=>["Septembre", "September", 30, 2], "10"=>["Octobre", "October", 31, 4]}
		@day = ["Lundi", "Mardi", "Mercredi" , "Jeudi", "Vendredi", "Samedi", "Dimanche"]
	end

	def reservation
		@date = "2015-#{params[:month]}-#{params[:day]}"
	end

	def create
		params[:description] = params[:description].gsub(/[<>]/, '')
		params[:resa]["description"] = params[:description]
		@intervenant = Calendrier.new(reservation_params)
		@intervenant.save
		redirect_to intervenants_path
	end

	private
	  def reservation_params
	    params.require(:resa).permit(:nom, :prenom, :email, :telephone, :date, :description)
	  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		array_des_id=[]
		Citation.all.map{|citation| array_des_id << citation.id}
	  	tirage_citation = array_des_id.sample
	  	@citation = Citation.find(tirage_citation)
	end

  def promo
    @simploniens = User.simploniens
  end

  def projets
    @images_projet = Dir.glob("app/assets/images/projets/*")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "ok"
      redirect_to root_path
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
      log_out if logged_in?
      log_out
      redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :redirect_unlogged_users

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    if @user.update user_params
      redirect_to promo_path
    else
      render 'edit', notice: "#{user_params} n'est pas disponible"
    end
  end

  private
    def user_params
      params.require(:user).permit(:id, :name, :email, :password,:password_confirmation, :title, :tags, :desc, :linkedin, :twitter, :github, :online)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/calendrier_helper.rb
module CalendrierHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
     def redirect_unlogged_users
          redirect_to root_path unless logged_in?
     end

	def log_in(user)
    	     session[:user_id] = user.id
	end

     def current_user
          @current_user ||= User.find_by(id: session[:user_id])
     end

     def logged_in?
          !current_user.nil?
     end

     def log_out
          session.delete(:user_id)
          @current_user = nil
     end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="form">
	<h1>Editer l'article</h1>
	<div class="formulaire">
		<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
			<% if @article.errors.any? %>
			    <div id="error_explanation">
			        <%= pluralize(@article.errors.count, "erreur") %> : Impossible de sauvegarder l'article, veuillez remplir tous les champs
			        <ul>
						<% @article.errors.full_messages.each do |msg| %>
          				<li><%= msg %></li>
       				 <% end %>
       				</ul> 
			    </div>
		  <% end %>
		  <p class="selecteur">
		    <%= f.label :jour %>
		    <%= f.select :day, (1..31).to_a %>
		    <%= f.label :mois %>
		    <%= f.select :month, ["janv", "févr", "mars", "avr", "mai", "juin", "juil", "août", "sept", "oct", "nov", "déc"] %>
		    <%= f.label :année %>
		    <%= f.select :year, ["2015", "2016", "2017"] %>
		  </p> 
		  <p>
		    <%= f.label :titre %><br>
		    <%= f.text_area :title, :class => "text_field" %>
		  </p>
		  <p>
		    <%= f.label :"sous-titre" %><br>
		    <%= f.text_area :subtitle, :class => "text_field" %>
		  </p>
		  <p>
		    <%= f.label :texte %><br>
		    <%= f.text_area :content %>
		  </p>
		 
		  <p>
		    <%= f.submit 'Enregistrer les modifications' %>
		  </p>
		<% end %>
	</div>
</div>

app/views/articles/index.html.erb
<div class="label">
    <%= flash[:notice] %>
</div>
<% if logged_in? %>
  <div class="nav_blog">
    <%= link_to "nouvel article", new_article_path %>
  </div>
<% end %>
<article class="container_blog">
<% @articles.reverse.each do |article| %>
  <div class="article">
    <div class="info_blog">
      <div class="day">
        <%= article.day %>
      </div>
      <div class="date_blog">
        <div class="month">
          <%= article.month %>
        </div>
        <div class="year">
          <%= article.year %>
        </div>
      </div>             
      <h1 class="title">
        <%= article.title %>
      </h1>
    </div> 
    <h3 class="subtitle">
      <%= article.subtitle %>
    </h3>
    <div class="content">
      <%= simple_format article.content %>
    </div>
  </div>
<% end %>
</article>

app/views/articles/new.html.erb
<div class="form">
	<h1>Nouvel article</h1>
	  <% if @article.errors.any? %>
      <div id="error_explanation">
        <%= pluralize(@article.errors.count, "erreur") %> : Impossible de sauvegarder l'article, veuillez remplir tous les champs.
      	<ul>
    			<% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
     		</ul> 
      </div>
  <% end %>
	<%= form_for :article, url: articles_path  do |f| %>
    <p class="selecteur">
      <%= f.label :"jour" %>
      <%= f.select :day, (1..31).to_a %>
      <%= f.label :mois %>
      <%= f.select :month, ["janv", "févr", "mars", "avr", "mai", "juin", "juil", "août", "sept", "oct", "nov", "déc"] %>
      <%= f.label :année %>
      <%= f.select :year, ["2015", "2016", "2017"] %>
    </p> 
    <p>
    <%= f.label :titre %><br>
    <%= f.text_area :title, :class => "text_field" %>
    </p>
    <p>
    <%= f.label :"sous-titre" %><br>
    <%= f.text_area :subtitle, :class => "text_field" %>
    </p>
    <p>
    <%= f.label :texte %><br>
    <%= f.text_area :content %>
    </p>
    <%= f.submit 'Enregistrer le nouvel article', class: "submit_btn" %>
	<% end %>
</div>

app/views/articles/show.html.erb
<div class="article">
	<div class='info_blog'>
		<div class="day">
      	 <%= @article.day %>
     	</div>
    	<div class='date_blog'>
   			<div class="month">
       			<%= @article.month %>
     		</div>
    		<div class="year">
       			<%= @article.year %>
    		</div>
    	</div>            
		<p class="title">
	 		<%= @article.title %>
		</p>
	</div>	 
	<p class="subtitle">
	  <%= @article.subtitle %>
	</p>
	<div class="content">
	  <%= simple_format @article.content%>
	</div>	
    <%= link_to (image_tag('home.png')), articles_path, :class => "home" %>
    <div class='icon_blog'>
		<%= link_to (image_tag('edit.png')), edit_article_path(@article) %>
		<%= link_to (image_tag('delete.png')), article_path(@article),
	              method: :delete,
	              data: { confirm: 'Etes-vous sûr ?' } %>
	</div>              
</div>

app/views/calendrier/reservation.erb
<div class="container-fluid resa-background">

	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<h1 class="resa-titre text-center">Formulaire Intervenant</h1>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<form method="post" action="/intervenants/reservation" id="form_resa">
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input type="text" class="input__field input__field--resa" name="resa[nom]" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">Nom</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input type="text" class="input__field input__field--resa" name="resa[prenom]" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">Prénom</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input type="text" class="input__field input__field--resa" name="resa[email]" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">E-mail</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input type="text" class="input__field input__field--resa" name="resa[telephone]" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">Téléphone</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<input readonly type="date" class="input__field input__field--resa date" name="resa[date]" value="<%= @date %>" autocomplete="off">
					<label class="input__label input__label--resa">
						<span class="input__label-content input__label-content--resa">Date Réservée</span>
					</label>
					<svg class="graphic graphic--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,58.0c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,2.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="row space-textarea">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 input--resa">
					<textarea class="textarea" name="description"></textarea>
					<label class="textarea__label textarea__label--resa">
						<span class="textarea__label-content textarea__label-content--resa">Domaine d'activité</span>
					</label>
					<svg class="graphic graphic2--resa" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
						<path d="M0,56.5c0,0,298.666,0,399.333,0C448.336,56.5,513.994,46,597,46c77.327,0,135,10.5,200.999,10.5c95.996,0,402.001,0,402.001,0"/>
						<path d="M0,1.5c0,0,298.666,0,399.333,0C448.336,2.5,513.994,13,597,13c77.327,0,135-10.5,200.999-10.5c95.996,0,402.001,0,402.001,0"/>
					</svg>
				</div>
			</div>
			<div class="form-button">
				<a class="resa-btn-cancel" href="/intervenants">Annuler</a>
				<a class="resa-btn-valid" id="resa-submit" onclick="document.getElementById('form_resa').submit(); document.getElementById('resa-submit').removeAttribute('onclick');">Valider</a>
			</div>
		</form>
	</div>
</div>

app/views/calendrier/show.erb
<% if logged_in? %>
  <button class="resa-btn-valid">
    <%= link_to "Fermer la session", logout_path, method: :delete %>
  </button> 
<% else %>
<div class="resa-container"> 
  <% end %>  
  <div class="resa-container">
    <h1 class="resa-titre text-center">Calendrier des intervenants et des évènements 2015</h1>
    <% @month.each do |key,list| %>
      <div class="row">  
        <div class="resa-nom_mois">
          <%= list[0] %>
        </div>

        <div class="resa-calendrier">
          <div class="resa-mois">

            <% a = 1; b = 1; c = 1 %>

            <div class="resa-nom_jour">
              <% @day.each do |day| %>
              <div class="resa-jour">
                <%= day %>
              </div>
              <% end %>
            </div>

            <% while a < list[3] %>
            <% if b == 1 %>
            <div class="resa-semaine">
              <% end %>
              <div class="resa-jour">
              </div>
              <% a += 1; b += 1 %>
              <% end %>


              <% while c <= list[2] %>

              <% if b == 1 || b % 7 == 1 %>
              <div class="resa-semaine">
                <% end %>

                <% l = sprintf '%02d', c %>
                <% @date = [] %>
                <% @intervenant.each do |idate| %>
                <% @date << idate.date.strftime("%d-%m") %>
                <% end %>

                <% if @date.include?("#{l}-#{key}") %>
                <div class="resa-jour resa-indispo">
                  <%= c %>
                </div>
                <% elsif key == "08" && c < 17 %>
                <div class="resa-jour resa-weekend">
                  <%= c %>
                </div>
                <% elsif b % 7 == 6 %>
                <div class="resa-jour resa-weekend">
                  <a <% if logged_in? %> href="/intervenants/reservation/<%= l %>-<%= key %>" <% end %> >
                    <%= c %>
                  </a>
                </div>
                <% elsif b % 7 == 0 %>
                <div class="resa-jour resa-weekend">
                  <%= c %>
                </div>
                <% else %>
                <div class="resa-jour resa-dispo">
                  <a <% if logged_in? %> href="/intervenants/reservation/<%= l %>-<%= key %>" <% end %> >
                    <%= c %>         
                  </a>
                </div>
                <% end %>

                <% if b % 7 == 0 %>
              </div>
              <% end %>

              <% b += 1; c += 1 %>

              <% end %>

              <% while b % 7 != 1 %>
              <div class="resa-jour">

              </div>
              <% b += 1 %>
              <% end %>

            </div>
          </div>
        </div>

        <div class="resa-texte">
          <% @intervenant.each do |i| %>
          <% if i.date.strftime("%B") == list[1] %>
          <div class="resa-info">
            <div class="resa-date">
              <%= i.date.strftime("%e %B %Y").gsub(list[1], list[0]) %>: 
            </div>
            <div class="resa-nom">
              <%= i.prenom %>
              <%= i.nom %>
            </div>
            <div class="resa-contact">
              <%= i.description %>
              <% if logged_in? %>
              <br>Tel: <%= i.telephone %>
              <% end %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/home/_calltoaction.html.erb
<div class="calltoaction-button">
	<%= link_to image_tag("logosimplonve_bleu.svg", class: "polygone-bleu"), home_page_actions_path %>
	<%= link_to image_tag("logosimplonve_vert.svg", class: "polygone-vert") %>
</div>
<div class="intro_simplonve">
	<h2>Simplon.VE</h2>
  <p><%= t('calltoaction').html_safe %></p>
</div>

app/views/home/_cartographie.erb
<div class="bloc_logos">
	<div class="logo">
		<%= image_tag("logos/html-5.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/css-3.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/jquery.svg", class: "grayscale style_logo taille2") %>	
		<%= image_tag("logos/javascript.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/nodejs-icon.svg", class: "grayscale style_logo taille2") %>
	</div>
	<div class="logo">
		<%= image_tag("logos/rails.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/sinatra.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/python.svg", class: "grayscale style_logo taille2") %>
	</div>
	<div class="logo">
		<%= image_tag("logos/heroku.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/postgresql.svg", class: "grayscale style_logo taille2") %>	
		<%= image_tag("logos/mysql.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/wordpress-icon.svg", class: "grayscale style_logo taille2") %>
	</div>
	<div class="logo">
		<%= image_tag("logos/bootstrap.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/django.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/angular-icon.svg", class: "grayscale style_logo taille2") %>
		
	</div>
	<div class="logo">
		<%= image_tag("logos/git.svg", class: "grayscale style_logo taille2") %>
		<%= image_tag("logos/nginx.svg", class: "grayscale style_logo taille2") %>
	</div>
</div>

app/views/home/_chiffres_cles.html.erb
<div class="container-chiffres-cles">
  <h2>Sur 20 Simploniens de la 1ère promotion</h2>
</div>
<div class="container-chiffres-cles">
  <div class="box-chiffre">
    <h1>84%</h1>
    <p>de demandeurs d'emplois</p>
  </div>
  <div class="box-chiffre">
    <h1>75%</h1>
    <p>diplomés inférieurs ou = BAC+2</p>
  </div>
  <div class="box-chiffre">
    <h1>25%</h1>
    <p>de femmes</p>
  </div>
  <div class="box-chiffre">
    <h1>80%</h1>
    <p>d'Ardéchois</p>
  </div>
  <div class="box-chiffre">
    <h1>840h</h1>
    <p>de formation</p>
  </div>
  <div class="box-chiffre">
    <h1>2</h1>
    <p>projets pro à réaliser</p>
  </div>
  <div class="box-chiffre">
    <h1>70h</h1>
    <p>de stage en alternance</p>
  </div>
</div>

app/views/home/_ecran_accueil.erb
<div class="entete">
	<div class="logo">
		<%= link_to root_path do %>
      <%= image_tag("logosimplonveseul.svg", class: "logo_simplonve") %>
    <% end %>
	</div class="container">
	<div class="titre-logo">
    <%= t('slogan') %><br>
		<%= t('slogan2') %>
	</div>
</div>

app/views/home/_financeurs.html.erb
<div class="financeurs">
	<div class="logo">
		<%= link_to image_tag("logo_region_RA2.svg", class: "grayscale style_logo taille"), url_for(href="http://www.rhonealpes.fr/"), :target => :blank %>

		<%= link_to image_tag("logo_conseil_ardeche2.png", class: "grayscale style_logo taille"), url_for(href="http://www.ardeche.fr"), :target => :blank %>

		<%= link_to image_tag("logo_VE.jpg", class: "grayscale style_logo taille"), url_for(href="http://www.valeyrieux.fr/"), :target => :blank%>

		<%= link_to image_tag("Ville_le_Cheylard.png", class: "grayscale style_logo taille") , url_for(href="http://www.ville-lecheylard.fr/"), :target => :blank%>
	</div>
	<div class="logo">
		<%= link_to image_tag("logo_AGEFOS.jpg", class: "grayscale style_logo taille taille_mediaquery"), url_for(href="http://www.agefos-pme.com/"), :target => :blank %>
		<%= link_to image_tag("logo_fond_paritaire.jpg", class: "grayscale style_logo taille"), url_for(href="http://www.fpspp.org/portail/easysite/fpspp/"), :target => :blank %>
		<%= link_to image_tag("Logo_Pole_Emploi.png", class: "grayscale style_logo taille"), url_for(href="http://www.pole-emploi.fr/accueil/"), :target => :blank %>
		<%= link_to image_tag("logo_inforoutes.jpg", class: "grayscale style_logo taille"), url_for(href="http://www.inforoutes.fr/"), :target => :blank %>
	</div>
	<div class="logo">
		<%= link_to image_tag("logo-pcsoft.png", class: "grayscale style_logo taille"), url_for(href="http://www.pcsoft.fr/"), :target => :blank %>
	</div>
</div>

app/views/home/promo2.haml
%hr
%h2 PROMO #2
		
%p.annonce_promo2 Page en cours de construction !

app/views/layouts/_nav.erb
<nav class="layout_nav">
	<div id="nav-toggle"><div class="burger" ><span></span></div></div>
	<div class="liens">
    <%= link_to 'accueil', root_path, :class => "link_nav" %>
		<%= link_to 'simplon.ve ?', home_page_actions_path, :class => "link_nav" %>
    <%= link_to 'promo 1', promo_path, :class => "link_nav" %>
    <%= link_to 'promo 2', promo2_path, :class => "link_nav" %>
   <!--  <%= link_to 'intervenants', intervenants_path, :class => "link_nav" %> -->
		<%= link_to("#{current_user.name.split.first.capitalize}", edit_user_path(current_user), :class => "link_nav") if current_user %>
	</div>
</nav>

app/views/users/edit.haml
%h1 Edit
.row_user
  %p 
    Manque d'inspiration ? 
    =link_to "Observez comment les SimplonMars ont fait", "http://www.simplonmars.eu/nospromos.php" 
  = form_for(@user) do |f|
    = render 'shared/error_messages'
    = f.label :name, class: 'pretty_label'
    %p Nom + Prénom
    = f.text_field :name
    = f.label :email, class: 'pretty_label'
    %p Votre email pro, rendu public, sur lequel on pourra vous contacter
    = f.email_field :email       
    = f.label :job, class: 'pretty_label'
    %p Le titre du poste auquel vous prétendez (généralement ce que l'on marque en sous-titre d'un CV)
    = f.text_field :title
    = f.label :compétence, class: 'pretty_label'
    %p Attention, séparez vos compténces par des virgules ex: HTML,CSS,Jquery
    = f.text_field :tags
    = f.label :desc, class: 'pretty_label'
    %p Une petite phrase qui vous décris après la formation, sur ce que vous aimeriez faire plus tard
    = f.text_area :desc
    = f.label :linkedin, class: 'pretty_label'
    = f.text_field :linkedin
    = f.label :twitter, class: 'pretty_label'
    = f.text_field :twitter
    = f.label :github, class: 'pretty_label'
    = f.text_field :github
    = f.label :online, class: 'pretty_label'
    = f.check_box :online        
    = f.submit "Update vite !", class: "btn btn-primary"
= link_to "LogOut", sessions_path, method: :delete